In [1]:
import pandas as pd

### Import data

In [7]:
file_path = 'CMO-Historical-Data-Monthly (1).xlsx'
df = pd.read_excel(file_path, sheet_name= 'Monthly Prices', skiprows=4)

In [8]:
df

,Unnamed: 0,"Crude oil, average","Crude oil, Brent","Crude oil, Dubai","Crude oil, WTI","Coal, Australian","Coal, South African **","Natural gas, US","Natural gas, Europe","Liquefied natural gas, Japan",...,Aluminum,"Iron ore, cfr spot",Copper,Lead,Tin,Nickel,Zinc,Gold,Platinum,Silver
0,NaN,($/bbl),($/bbl),($/bbl),($/bbl),($/mt),($/mt),($/mmbtu),($/mmbtu),($/mmbtu),...,($/mt),($/dmtu),($/mt),($/mt),($/mt),($/mt),($/mt),($/troy oz),($/troy oz),($/troy oz)
1,1960M01,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,715.4,206.1,2180.4,1631,260.8,35.27,83.5,0.9137
2,1960M02,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,728.19,203.7,2180.4,1631,244.9,35.27,83.5,0.9137
3,1960M03,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,684.94,210.3,2173.8,1631,248.7,35.27,83.5,0.9137
4,1960M04,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,723.11,213.6,2178.2,1631,254.6,35.27,83.5,0.9137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,2024M03,83.545667,85.447,84.7,80.49,131.49,104.84,1.4999,8.553726,13.185629,...,2226.16,109.79,8689.13,2056.2,27450.46,17438.83,2461.04,2158.01,908.75,24.518
772,2024M04,88.011333,90.054,89.39,84.59,134.97,104.89,1.5967,9.085119,11.87777,...,2506.1,112.75,9464.43,2129.46,31774.5,18163.95,2732.74,2331.45,940.18,27.494
773,2024M05,81.445,81.995,83.53,78.81,142.01,105.63,2.1314,10.123066,12.162896,...,2564.54,118.88,10139.33,2220.81,32977.51,19586.98,2959.13,2351.13,1014.68,29.36
774,2024M06,81.205,82.555,82.17,78.89,135.1,105.3,2.5123,10.868978,12.130971,...,2497.61,107.45,9648.17,2147.1,32032.7,17498.01,2809.19,2326.44,985.08,29.577
775,2024M07,83.258667,85.296,83.94,80.54,137.55,105.31,2.0751,10.346819,12.088555,...,2349.13,106.85,9385.31,2106.94,31860.47,16334.88,2777.27,2398.2,978.8,29.773

### Process raw commodity data